version: '3.9'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"

  buf-lint:
    image: bufbuild/buf
    command:
      - lint
    working_dir: /workspace
    volumes:
      - "./event-scheduler-api/src/main/protobuf:/workspace"
